### ISSUE TITLE
Good initiative, but rather pointless

### ISSUE THREAD

**Issue by Addvilz** [iheanyi/speakers-who-want-a-platform#58]
> At times, we hear the excuse that there aren't enough people from underrepresented groups to reach out to

Except for certain, specific, cases where someone is approached to speak about something they are widely known to have expertise in, conference organizers in general are not reaching out to speakers individually - there are literally, millions upon millions of people out there who organizer could potentially invite, it's just not feasible, especially for organizers of smaller, localized conferences with more limited resources.

Usually planned conferences get announced, and then call for "papers" is issued to whoever would like to submit a talk / join a panel / whatever.

> or that they couldn't find any that wanted to participate. This list aims to fix that problem. 

What could indeed fix the problem you are trying to address (and maximum kudos for that), would be to aggregate upcoming conferences, locally and globally, and make them much more accessible by distributing the information on topics, location and more importantly, information about how to participate - how to join a panel, how to submit a talk, or any other ways of participation.

This would allow for everyone to have direct access to conferences, presenting and other opportunities of participation - whenever and on terms they choose to.

This is in addition to missing information in the list, like preferred topics, #23 and expertise - essential for organizers to figure who to approach, if that's what they decide to do.

**Comment by iheanyi** [comment]
Thanks for the suggestions. I'm working on revamping the documentation to suggest that people add their preferred topics of presentation. IN this regard, this list isn't meant as a means to "invite people to speak without submitting a CFP" but it could make it easier for conference organizers to find people and suggest that they submit a CFP to their conference. I don't know how it will be used. I'm just glad it exists. Thanks for your feedback,  I'm hoping to improve this repo and really appreciate it.

**Comment by mrmrs** [comment]
@Addvilz appreciate the suggestions but maybe consider framing this in a more positive manner? 
To suggest that this is rather pointless and that your idea is the solution seems a bit limiting. There are services that aggregate conferences and help people apply. This hasn't 'fixed' anything. It has made things better! To make progress, many efforts must move many needles. There likely will not be a one fell swoop solution.

In my experience, direct access isn't the only problem. I get invited to speak at events generally once every 3-4 weeks. When I show up, I am more often than not in the company of a lot of people that look just like me - this is not necessarily inviting or inclusive to underrepresented groups. To tip the scales, we need to encourage organizers to be more active and intentional about who they invite to speak. I think any resources that help amplify this message are anything but pointless. Would love to continue to get your feedback on how to improve this project, but please frame it in a more constructive manner.

**Comment by Addvilz** [comment]
> There are services that aggregate conferences and help people apply.

@mrmrs Can you link some of the ones meant for the speakers? I think a lot of people here would find it rather useful.

> I am more often than not in the company of a lot of people that look just like me - this is not necessarily inviting or inclusive to underrepresented groups.

I believe that to be a statistical reality - there is no need to turn it into anything more than that. But then again, it is a reality from your personal and limited point of view. It would be interesting to see you in a company of people who look like you at, for example, QCon Beijing. Then again, it would be even better for you to try and drop the "us and them" mindset, which only furthers the artificial divide between the groups, defined only by extra imposed labels you shouldn't really care that much about.

> To tip the scales, we need to encourage organizers to be more active and intentional about who they invite to speak.

 ... or, instead we could announce, collectively and unanimously, as organizers and participants, that we care not for what is the skin color, gender, sexual preference, nationality or whatnot else property of a speaker. All we want is quality talks fit for a topic of the conference.

And matter to the point, I find unbiased criticism an imposingly constructive motivator.

**Comment by iheanyi** [comment]
All righty, closing this issue cause it's already been answered and no point in keeping this issue open. Let's be civil here. If you find the repo pointless, that's on you. There are others that think otherwise. You don't have to use it if you don't want to. Take care.
