### ISSUE TITLE
Question: What's the definition of "underrepresented groups"?

### ISSUE THREAD

**Issue by atom-morgan** [iheanyi/speakers-who-want-a-platform#70]
See title

**Comment by iheanyi** [comment]
Underrepresented Groups are groups that are not as prominent within the tech industry. People of color, women, those with disabilities, LGBT individuals, etc.

**Comment by jalcine** [comment]
Is this worth including into the README?

**Comment by atom-morgan** [comment]
What's the order of operations here? If you're a straight white woman with a disability, do you qualify? What about straight white male?

**Comment by tbarn** [comment]
How would an order of operations be useful? I've only seen them used to oppress further, but I'm open to new ideas on it.

**Comment by atom-morgan** [comment]
I'm not saying it is useful. I'm just asking if it exists in this context.

**Comment by jalcine** [comment]
It doesn't because it's irrelevant. To be frank, a question like that reads as mildly derailing and analytical for no intent outside of picking one's brain for the lulz. If you want to continue this more, I recommend using an alternate forum that's targeted for the exploration of said question.

The _purpose_ of this repository is to highlight and bring note to **underrepresented groups**. By definition, that means anyone not considered the stereotypical norm that the consumer electronics and development industry is currently shipping.

If you want to continue this, feel free to email me personally or reach out on Twitter.
